Hotel_Tunisie_Referentiel:
    resource: "@BackResaBookingBundle/Resources/config/routing/configuration.yml"
    prefix:   /configuration

Hotel_Tunisie_hotels:
    resource: "@BackResaBookingBundle/Resources/config/routing/hotels.yml"
    prefix:   /hotels