back_maritime_reservation_liste:
    path:      /liste/{page}/{etat}/{sort}/{direction}
    defaults: { _controller: BackBilletterieMaritimeBundle:Maritime:liste,page:1,etat:1,sort:r.id,direction:desc }

back_maritime_reservation_consultation:
    path:      /consulter/{id}
    defaults: { _controller: BackBilletterieMaritimeBundle:Maritime:consulter }

back_maritime_reservation_reçu:
    path:     /recus/{id}
    defaults: { _controller: BackBilletterieMaritimeBundle:Maritime:recu }

back_maritime_reservation_delete:
    path:      /back_maritime_reservation_delete/{id}
    defaults: { _controller: BackBilletterieMaritimeBundle:Maritime:delete }

back_maritime_reservation_prendrecharge:
    path:      /encharge/{id}
    defaults: { _controller: BackBilletterieMaritimeBundle:Maritime:prendreEnCharge }

back_maritime_reservation_validation:
    path:      /validation/{id}
    defaults: { _controller: BackBilletterieMaritimeBundle:Maritime:valider }

back_maritime_reservation_remise:
    path:      /remise/{id}
    defaults: { _controller: BackBilletterieMaritimeBundle:Maritime:remise }

back_maritime_reservation_total:
    path:      /total/{id}
    defaults: { _controller: BackBilletterieMaritimeBundle:Maritime:total }

back_maritime_reservation_annuler:
    path:      /annuler/{id}
    defaults: { _controller: BackBilletterieMaritimeBundle:Maritime:annuler }