back_crm_client:
    resource: "@BackUserBundle/Resources/config/routing/client.yml"
    prefix:   /client
    
back_crm_fournisseur:
    resource: "@BackUserBundle/Resources/config/routing/fournisseur.yml"
    prefix:   /fournisseur