services:
    names:
        class: Back\VoyageOrganiseBundle\Twig\Extension\NamesExtension
        tags:
            - { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"