services:
    namesVO:
        class: Back\VoyageOrganiseBundle\Twig\Extension\NamesExtension
        tags:
            - { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"
            
    reservationVO:
        class: Back\VoyageOrganiseBundle\Services\ReservationService
        arguments:
            - @doctrine.orm.entity_manager
            - @session
            - @service_container
            - @mailer
            - @templating