config_front_voyageorganise:
    resource: "@FrontConfigBundle/Resources/config/routing/voyageorganise.yml"
    prefix:   /VoyageOrganise

config_front_hoteltunisie:
    resource: "@FrontConfigBundle/Resources/config/routing/hoteltunisie.yml"
    prefix:   /HotelTunisie

config_front_programme:
    resource: "@FrontConfigBundle/Resources/config/routing/programme.yml"
    prefix:   /Programme

config_front_accueil:
    resource: "@FrontConfigBundle/Resources/config/routing/accueil.yml"
    prefix:   /acuueil