services:
    namesPR:
        class: Back\ProgrammeBundle\Twig\Extension\NamesExtension
        tags:
            - { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"
            
    reservationPR:
        class: Back\ProgrammeBundle\Services\ReservationService
        arguments:
            - @doctrine.orm.entity_manager
            - @session
            - @service_container
            - @mailer
            - @templating