Administration_users:
    resource: "@BackAdministrationBundle/Resources/config/routing/users.yml"
    prefix:   /utilisateurs

Administration_b2b:
    resource: "@BackAdministrationBundle/Resources/config/routing/b2b.yml"
    prefix:   /b2b

