Administration_users:
    resource: "@BackAdministrationBundle/Resources/config/routing/users.yml"
    prefix:   /utilisateurs

Administration_client:
    resource: "@BackAdministrationBundle/Resources/config/routing/client.yml"
    prefix:   /client

Administration_configuration:
    resource: "@BackAdministrationBundle/Resources/config/routing/configuration.yml"
    prefix:   /configuration
