Administration_users:
    resource: "@BackAdministrationBundle/Resources/config/routing/users.yml"
    prefix:   /utilisateurs

Administration_b2b:
    resource: "@BackAdministrationBundle/Resources/config/routing/b2b.yml"
    prefix:   /b2b

Administration_client:
    resource: "@BackAdministrationBundle/Resources/config/routing/client.yml"
    prefix:   /client

