services:
    names:
        class: Back\HotelTunisieBundle\Twig\Extension\NamesExtension
        tags:
            - { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"

    mailerService:
        class: Back\AdministrationBundle\Services\MailerService
        arguments:
            - @doctrine.orm.entity_manager
            - @session
            - @service_container
            - @mailer
            - @templating

    rolesService:
        class: Back\AdministrationBundle\Services\RolesService
        arguments:
            - @service_container