list_hotels:
    path:     /
    defaults: { _controller: BackHotelTunisieBundle:Hotels:liste }

modif_hotel:
    path:     /modif/{id}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:modif}

change_etat:
    path:     /etat/{id}/{etat}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:etat}

supprimer_hotel:
    path:     /supprimer/{id}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:supprimer}

ajout_hotel:
    path:     /ajout
    defaults: { _controller: BackHotelTunisieBundle:Hotels:ajout }

photos_hotel:
    path:     /modif/{id}/photos
    defaults: { _controller: BackHotelTunisieBundle:Hotels:photos }

stopsales_hotel:
    path:     /modif/{id}/stopsales
    defaults: { _controller: BackHotelTunisieBundle:Hotels:stopsales }

supprimer_stopsales_hotel:
    path:     /stopsales/delete/{id}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:suppStopSales }
    
fiche_technique:
    path:     /modif/{id}/fiche_technique
    defaults: { _controller: BackHotelTunisieBundle:Hotels:ficheTechnique }
    
saison_base:
    path:     /modif/{id}/saison_base
    defaults: { _controller: BackHotelTunisieBundle:Hotels:saisonBase }
    
saison_chambres:
    path:     /modif/{id}/saison_chambres
    defaults: { _controller: BackHotelTunisieBundle:Hotels:saisonChambres }
    
saison_reduction:
    path:     /modif/{id}/saison_reduction
    defaults: { _controller: BackHotelTunisieBundle:Hotels:saisonReduc }