list_hotels:
    path:     /list/{page}/{ville}/{chaine}/{categorie}/{etat}/{libelle}/{sort}/{direction}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:liste,page:1,ville:all,categorie:all,etat:all,chaine:all,libelle:all,sort:h.id,direction:desc }

filtre_hotels:
    path:     /Filtrehotel
    defaults: { _controller: BackHotelTunisieBundle:Hotels:filtre }

generer_tarif_hotels:
    path:     /tarif_hotels
    defaults: { _controller: BackHotelTunisieBundle:Hotels:genereTarifs }

generer_tarif_hotels_liste:
    path:     /tarif_hotels/liste/{debut}/{fin}/{amicale}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:genereTarifsListe,amicale:null }

modif_hotel:
    path:     /modif/{id}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:modif}

chambre_hotel:
    path:     /modif/{id}/chambres
    defaults: { _controller: BackHotelTunisieBundle:Hotels:hotelChambre}

change_etat:
    path:     /etat/{id}/{etat}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:etat}

supprimer_hotel:
    path:     /supprimer/{id}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:supprimer}

ajout_hotel:
    path:     /ajout
    defaults: { _controller: BackHotelTunisieBundle:Hotels:ajout }

photos_hotel:
    path:     /modif/{id}/photos
    defaults: { _controller: BackHotelTunisieBundle:Hotels:photos }

stopsales_hotel:
    path:     /modif/{id}/stopsales
    defaults: { _controller: BackHotelTunisieBundle:Hotels:stopsales }

supprimer_stopsales_hotel:
    path:     /stopsales/delete/{id}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:suppStopSales }
    
fiche_technique:
    path:     /modif/{id}/fiche_technique
    defaults: { _controller: BackHotelTunisieBundle:Hotels:ficheTechnique }    

article_hotel:
    path:     /modif/{id}/convention/{id2}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:article,id2:null }


add_file_to_contrat:
    path:     /add_file_to_contrat/{id}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:addfileToContrat }

supprimer_article_hotel:
    path:     /supprimer_contrats_hotel/{id}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:deleteArticle }