list_hotels:
    path:     /
    defaults: { _controller: BackHotelTunisieBundle:Hotels:liste }

modif_hotel:
    path:     /modif/{id}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:modif}

change_etat:
    path:     /etat/{id}/{etat}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:etat}

supprimer_hotel:
    path:     /supprimer/{id}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:supprimer}

ajout_hotel:
    path:     /ajout
    defaults: { _controller: BackHotelTunisieBundle:Hotels:ajout }

photos_hotel:
    path:     /modif/{id}/photos
    defaults: { _controller: BackHotelTunisieBundle:Hotels:photos }

stopsales_hotel:
    path:     /modif/{id}/stopsales
    defaults: { _controller: BackHotelTunisieBundle:Hotels:stopsales }

supprimer_stopsales_hotel:
    path:     /stopsales/delete/{id}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:suppStopSales }
    
fiche_technique:
    path:     /modif/{id}/fiche_technique
    defaults: { _controller: BackHotelTunisieBundle:Hotels:ficheTechnique }
    
saison_base:
    path:     /modif/{id}/saison_base
    defaults: { _controller: BackHotelTunisieBundle:Hotels:saisonBase }
    
saison_chambres:
    path:     /modif/{id}/saison_chambres
    defaults: { _controller: BackHotelTunisieBundle:Hotels:saisonChambres }
    
delete_saison_chambres:
    path:     /delete_chambre_saison/{id}/{hotel}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:deleteSaisonChambres }
    
saison_reduction:
    path:     /modif/{id}/saison_reduction
    defaults: { _controller: BackHotelTunisieBundle:Hotels:saisonReduc }
    
saison_arrangements:
    path:     /modif/{id}/saison_arrangements
    defaults: { _controller: BackHotelTunisieBundle:Hotels:saisonArrangements }
    
delete_saison_arrangements:
    path:     /delete_arrangement_saison/{id}/{hotel}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:deleteSaisonArragements }
        
saison_supp_chambres:
    path:     /modif/{id}/saison_supp_chambres
    defaults: { _controller: BackHotelTunisieBundle:Hotels:saisonSuppChambres }
    
delete_saison_supp_chambres:
    path:     /delete_supp_chambre_saison/{id}/{hotel}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:deleteSaisonSuppChambres }    
        
saison_vues:
    path:     /modif/{id}/saison_vue
    defaults: { _controller: BackHotelTunisieBundle:Hotels:saisonVues }
    
delete_saison_vues:
    path:     /delete_vue_saison/{id}/{hotel}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:deleteSaisonVues }    