list_hotels:
    path:     /list/{page}/{ville}/{chaine}/{categorie}/{etat}/{libelle}/{sort}/{direction}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:liste,page:1,ville:all,categorie:all,etat:all,chaine:all,libelle:all,sort:h.libelle,direction:asc }

filtre_hotels:
    path:     /Filtrehotel
    defaults: { _controller: BackHotelTunisieBundle:Hotels:filtre }

modif_hotel:
    path:     /modif/{id}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:modif}

chambre_hotel:
    path:     /modif/{id}/chambres
    defaults: { _controller: BackHotelTunisieBundle:Hotels:hotelChambre}

change_etat:
    path:     /etat/{id}/{etat}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:etat}

supprimer_hotel:
    path:     /supprimer/{id}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:supprimer}

ajout_hotel:
    path:     /ajout
    defaults: { _controller: BackHotelTunisieBundle:Hotels:ajout }

photos_hotel:
    path:     /modif/{id}/photos
    defaults: { _controller: BackHotelTunisieBundle:Hotels:photos }

stopsales_hotel:
    path:     /modif/{id}/stopsales
    defaults: { _controller: BackHotelTunisieBundle:Hotels:stopsales }

supprimer_stopsales_hotel:
    path:     /stopsales/delete/{id}
    defaults: { _controller: BackHotelTunisieBundle:Hotels:suppStopSales }
    
fiche_technique:
    path:     /modif/{id}/fiche_technique
    defaults: { _controller: BackHotelTunisieBundle:Hotels:ficheTechnique }    