Hotel_Tunisie_Reporting_NombreReservation_form:
    path:     /nombreReservation
    defaults: { _controller: BackHotelTunisieBundle:Reporting:nombreReservation }

Hotel_Tunisie_Reporting_NombreReservation_stat:
    path:     /nombreReservation_state/{annee}/{mois}/{etat}/{regions}/{hotels}/{users}
    defaults: { _controller: BackHotelTunisieBundle:Reporting:nombreReservationRapport }
  
Hotel_Tunisie_Reporting_NombreNuitee_form:
    path:     /nombreNuitee
    defaults: { _controller: BackHotelTunisieBundle:Reporting:nombreNuitee }
    
Hotel_Tunisie_Reporting_NombreNuitee_stat:
    path:     /nombreNuitee_state/{annee}/{mois}/{etat}/{regions}/{hotels}/{users}
    defaults: { _controller: BackHotelTunisieBundle:Reporting:nombreNuiteeRapport }
    
    
Hotel_Tunisie_Reporting_ChiffreAffaire_form:
    path:     /chiffreAffaire
    defaults: { _controller: BackHotelTunisieBundle:Reporting:chiffreAffaire }
    
Hotel_Tunisie_Reporting_ChiffreAffaire_stat:
    path:     /chiffreAffaire_state/{annee}/{mois}/{etat}/{regions}/{hotels}/{users}
    defaults: { _controller: BackHotelTunisieBundle:Reporting:chiffreAffaireRapport }