new_reservation:
    path:     /
    defaults: { _controller: BackHotelTunisieBundle:Reservation:new }

gey_saison_ajax:
    path:     /gey_saison_ajax
    defaults: { _controller: BackHotelTunisieBundle:Reservation:saisonAjax }

ajax_ville_to_hotel:
    path:     /ajax_ville_to_hotel
    defaults: { _controller: BackHotelTunisieBundle:Reservation:ajaxVille }
    
formulaire_reservation:
    path:     /formulaire
    defaults: { _controller: BackHotelTunisieBundle:Reservation:formulaire }
    
details_reservation:
    path:     /details
    defaults: { _controller: BackHotelTunisieBundle:Reservation:details }
    
save_reservation:
    path:     /save
    defaults: { _controller: BackHotelTunisieBundle:Reservation:save }