liste_reservations:
    path:     /liste/{page}/{etat}/{amicale}/{sort}/{direction}
    defaults: { _controller: BackHotelTunisieBundle:Reservation:liste,page:1,etat:1,amicale:all,sort:r.id,direction:desc }

consulter_reservation:
    path:     /consulter/{id}
    defaults: { _controller: BackHotelTunisieBundle:Reservation:consulter }

valider_reservation:
    path:     /valider/{id}
    defaults: { _controller: BackHotelTunisieBundle:Reservation:valider }

remise_reservation:
    path:     /remise/{id}
    defaults: { _controller: BackHotelTunisieBundle:Reservation:remise }

recus_reservation:
    path:     /recus/{id}
    defaults: { _controller: BackHotelTunisieBundle:Reservation:recus }

voucher_reservation:
    path:     /voucher/{id}
    defaults: { _controller: BackHotelTunisieBundle:Reservation:voucher }

voucher_prix_reservation:
    path:     /voucher_prix/{id}
    defaults: { _controller: BackHotelTunisieBundle:Reservation:voucherPrix }

delete_reservation:
    path:     /delete_reservation/{id}
    defaults: { _controller: BackHotelTunisieBundle:Reservation:delete }

annuler_reservation:
    path:     /annuler_reservation/{id}
    defaults: { _controller: BackHotelTunisieBundle:Reservation:annuler }
    
filtre_reservations:
    path:     /filtre_liste
    defaults: { _controller: BackHotelTunisieBundle:Reservation:filtre }
    
prise_en_charge_reservations:
    path:     /prise_en_charge_reservations/{id}
    defaults: { _controller: BackHotelTunisieBundle:Reservation:prisEnCharge }

new_reservation:
    path:     /
    defaults: { _controller: BackHotelTunisieBundle:Reservation:new }

gey_saison_ajax:
    path:     /gey_saison_ajax
    defaults: { _controller: BackHotelTunisieBundle:Reservation:saisonAjax }

ajax_ville_to_hotel:
    path:     /ajax_ville_to_hotel
    defaults: { _controller: BackHotelTunisieBundle:Reservation:ajaxVille }
    
formulaire_reservation:
    path:     /formulaire
    defaults: { _controller: BackHotelTunisieBundle:Reservation:formulaire }
    
details_reservation:
    path:     /details
    defaults: { _controller: BackHotelTunisieBundle:Reservation:details }
    
save_reservation:
    path:     /save
    defaults: { _controller: BackHotelTunisieBundle:Reservation:save }
    
renotifier_hotel:
    path:     /renotifier_hotel/{id}
    defaults: { _controller: BackHotelTunisieBundle:Reservation:notifier }