generer_saison:
    path:     /modif/{id}/saisons/generer
    defaults: { _controller: BackHotelTunisieBundle:Saisons:Generer }
    
liste_saison:
    path:     /modif/{id}/saisons/
    defaults: { _controller: BackHotelTunisieBundle:Saisons:liste }

PeriodeSaison:
    path:     /saison/SaisonPeriode/{id}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:periode }

GeneralSaison:
    path:     /saison/SaisonGeneral/{id}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:general }

OccChambreSaison:
    path:     /saison/SaisonOccChambre/{id}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:occChambre }

ArrangementSaison:
    path:     /saison/SaisonArrangement/{id}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:arrangement }

ReductionSaison:
    path:     /saison/SaisonReduction/{id}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:reduction }

SupplementSaison:
    path:     /saison/SaisonSupplement/{id}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:supplement }

AutreChambreSaison:
    path:     /saison/SaisonAutreChambre/{id}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:autreChambre }

VuesSaison:
    path:     /saison/SaisonVue/{id}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:vue }

WeekendSaison:
    path:     /saison/SaisonWeekend/{id}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:weekend }

AutreSuppSaison:
    path:     /saison/SaisonAutreSupp/{id}/{id2}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:autreSupp,id2:null }

deleteAutreSupp:
    path:     /DeleteSaisonAutreSupp/{id}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:deleteAutreSupp }

AutreReducSaison:
    path:     /saison/SaisonAutreReduc/{id}/{id2}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:autreReduc,id2:null }

deleteAutreReduc:
    path:     /DeleteSaisonAutreReduc/{id}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:deleteAutreReduc }
    
PrixSaison:
    path:     /saison/SaisonPrix/{id}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:prix }

generate_frais_autre_chambre:
    path:     /saison/generate_frais_autre_chambre/{saison}/{chambre}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:generateFraisChambre }

saison_frais_autre_chambre:
    path:     /saison/frais_autre_chambre/{id}/{chambre}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:fraisChambre }

saison_delete_frais_autre_chambre:
    path:     /saison_delete_frais_autre_chambre/{id}
    defaults: { _controller: BackHotelTunisieBundle:Saisons:deleteFraisChambre }