back_bien_etre:
    resource: "@BackBienEtreBundle/Resources/config/routing.yml"
    prefix:   /admin/bien_etre

front_config:
    resource: "@FrontConfigBundle/Resources/config/routing.yml"
    prefix:   /admin/FrontOffice

front_general:
    resource: "@FrontGeneralBundle/Resources/config/routing.yml"
    prefix:   /

back_billetterie_maritime:
    resource: "@BackBilletterieMaritimeBundle/Resources/config/routing.yml"
    prefix:   /admin

espace_client:
    resource: "@EspaceClientBundle/Resources/config/routing.yml"
    prefix:   /

back_programme:
    resource: "@BackProgrammeBundle/Resources/config/routing.yml"
    prefix:   /admin/programme

back_voyage_organise:
    resource: "@BackVoyageOrganiseBundle/Resources/config/routing.yml"
    prefix:   /admin/voyage_organise

back_administration:
    resource: "@BackAdministrationBundle/Resources/config/routing.yml"
    prefix:   /admin/administration

back_commercial:
    resource: "@BackCommercialBundle/Resources/config/routing.yml"
    prefix:   /admin/commercial

#Hotel en tunisie
back_hotel_tunisie:
    resource: "@BackHotelTunisieBundle/Resources/config/routing.yml"
    prefix:   /admin/hotel_tunisie

#FosUserBundle
back_user:
    resource: "@BackUserBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#Back Office
back_general:
    resource: "@BackGeneralBundle/Resources/config/routing.yml"
    prefix:   /admin

#liip immage Bundle
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"