back_administration:
    resource: "@BackAdministrationBundle/Resources/config/routing.yml"
    prefix:   /admin/administration

back_commercial:
    resource: "@BackCommercialBundle/Resources/config/routing.yml"
    prefix:   /commercial

#Hotel en tunisie
back_hotel_tunisie:
    resource: "@BackHotelTunisieBundle/Resources/config/routing.yml"
    prefix:   /admin/hotel_tunisie

#FosUserBundle
back_user:
    resource: "@BackUserBundle/Resources/config/routing.yml"
    prefix:   /
    
#Fos User Bundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#Back Office
back_general:
    resource: "@BackGeneralBundle/Resources/config/routing.yml"
    prefix:   /admin

#Front Office
front_general:
    resource: "@FrontGeneralBundle/Resources/config/routing.yml"
    prefix:   /

#liip immage Bundle
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"