back_resa_booking:
    resource: "@BackResaBookingBundle/Resources/config/routing.yml"
    prefix:   /

espace_client:
    resource: "@EspaceClientBundle/Resources/config/routing.yml"
    prefix:   /espace_client

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

back_general:
    resource: "@BackGeneralBundle/Resources/config/routing.yml"
    prefix:   /admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

get_all_reservations:
    path:     /all
    defaults: { _controller: BackGeneralBundle:Default:allReservation }

front_config:
    resource: "@FrontConfigBundle/Resources/config/routing.yml"
    prefix:   /admin/FrontOffice

front_general:
    resource: "@FrontGeneralBundle/Resources/config/routing.yml"
    prefix:   /