back_voyages_organises_reservation_ajouter:
    path:     /ajouter
    defaults: { _controller: BackVoyageOrganiseBundle:Reservation:ajouter }

back_voyages_organises_reservation:
    path:     /liste/{page}
    defaults: { _controller: BackVoyageOrganiseBundle:Reservation:liste,page:1 }