back_vo_liste:
    path:     /liste/{page}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:liste,page:1 }

back_vo_supprimer:
    path:     /back_vo_supprimer/{id}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:supprimer }

back_vo_ajouter:
    path:     /ajouter/{id}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:ajouter,id:null }

back_vo_descriptions:
    path:     /ajouter/{voyage}/description/{id}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:description,id:null }

back_vo_descriptions_delete:
    path:     /back_vo_descriptions_delete/{id}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:SupprimerDescription }

back_vo_photos:
    path:     /ajouter/{voyage}/photo
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:photo }

back_vo_photos_delete:
    path:     /back_vo_photos_delete/{id}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:SupprimerPhoto }

back_vo_periode:
    path:     /ajouter/{voyage}/periodes/{id}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:periode,id:null }

back_vo_periode_delete:
    path:     /back_vo_periodes_delete/{id}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:SupprimerPeriode}

back_vo_pack:
    path:     /ajouter/{voyage}/pack/{id}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:pack,id:null }

back_vo_pack_delete:
    path:     /back_vo_pack_delete/{id}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:SupprimerPack}

back_vo_ligne_pach_delete:
    path:     /back_vo_ligne_pach_delete/{id}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:SupprimerPackLigne}

back_vo_circuit:
    path:     /ajouter/{voyage}/circuit/{id}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:circuit,id:null }

back_vo_circuit_delete:
    path:     /back_vo_circuit_delete/{id}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:SupprimerCircuit}

back_vo_frais:
    path:     /ajouter/{voyage}/frais/{id}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:frais,id:null }

back_vo_frais_delete:
    path:     /back_vo_frais_delete/{id}
    defaults: { _controller: BackVoyageOrganiseBundle:VoyageOrganise:SupprimerFrais}