<?php

namespace Back\ProgrammeBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodeRepository extends EntityRepository
{
}
