front_bienetre_liste:
    path:     /liste/{page}/{produits}/{sort}/{direction}/{name}
    defaults: { _controller: FrontGeneralBundle:BienEtre:liste,page:1,name:null,produits:all,sort:p.libelle,direction:asc}
    requirements:
        page:  \d+
        
front_bienetre_sort:
    path:     /sort/{produits}/{name}
    defaults: { _controller: FrontGeneralBundle:BienEtre:sort,produits:all,name:null }

front_bienetre_success:
    path:     /success/{id}
    defaults: { _controller: FrontGeneralBundle:BienEtre:success }
    requirements:
        id:  \d+
    
front_produit_details:
    path:     /{slug}/{date}
    defaults: { _controller: FrontGeneralBundle:BienEtre:details,date:null }
    
front_bienetre_reservation:
    path:     /reservation/{slug}/{date}/{tarif}
    defaults: { _controller: FrontGeneralBundle:BienEtre:reservation }