front_hoteltunisie_accueil:
    path:     /
    defaults: { _controller: FrontGeneralBundle:HotelTunisie:accueil }
    
front_hoteltunisie_list:
    path:     /liste/{page}/{categorie}/{chaine}/{ville}/{tag}/{promotion}/{name}
    defaults: { _controller: FrontGeneralBundle:HotelTunisie:liste,page:1,categorie:all,tag:all,promotion:no,chaine:all,ville:all,name:null }
    requirements:
        page:  \d+
    
front_hoteltunisie_filtre:
    path:     /filtre/{page}/{categorie}/{chaine}/{ville}/{tag}/{promotion}/{name}
    defaults: { _controller: FrontGeneralBundle:HotelTunisie:filtre,page:1,categorie:all,tag:all,chaine:all,promotion:no,ville:all,name:null }
    requirements:
        page:  \d+
    
front_hoteltunisie_details:
    path:     /{slug}
    defaults: { _controller: FrontGeneralBundle:HotelTunisie:details }
    
front_hoteltunisie_edit_periode:
    path:     /{slug}/editer_periode
    defaults: { _controller: FrontGeneralBundle:HotelTunisie:editPeriode }
    
front_hoteltunisie_reservation:
    path:     /booking/{slug}/reservation
    defaults: { _controller: FrontGeneralBundle:HotelTunisie:reservation }
    
front_hoteltunisie_tarif_dispo:
    path:     /{slug}/tarif_dispo
    defaults: { _controller: FrontGeneralBundle:HotelTunisie:tarifDispo }
    
front_hoteltunisie_thankyou:
    path:     /{slug}/success/{reservation}
    defaults: { _controller: FrontGeneralBundle:HotelTunisie:thankyou }