front_hoteltunisie_accueil:
    path:     /
    defaults: { _controller: FrontGeneralBundle:HotelTunisie:accueil }
    
front_hoteltunisie_list:
    path:     /liste/{page}/{categorie}/{chaine}/{ville}/{name}
    defaults: { _controller: FrontGeneralBundle:HotelTunisie:liste,page:1,categorie:all,chaine:all,ville:all,name:null }
    requirements:
        page:  \d+