front_paiement_notification:
    path:     /notification.php
    defaults: { _controller: FrontGeneralBundle:Paiement:notification }

front_paiement_succes:
    path:     /succes.php
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'FrontGeneralBundle::succes.html.twig'

front_paiement_echec:
    path:     /echec.php
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'FrontGeneralBundle::echec.html.twig'