front_programme_accueil:
    path:     /
    defaults: { _controller: FrontGeneralBundle:Programme:accueil }
    
front_programme_liste:
    path:     /liste/{page}/{themes}/{sort}/{direction}/{name}
    defaults: { _controller: FrontGeneralBundle:Programme:liste,page:1,themes:all,name:null,sort:p.libelle,direction:asc }
    requirements:
        page:  \d+

front_programme_sort:
    path:     /sort/{themes}/{name}
    defaults: { _controller: FrontGeneralBundle:Programme:sort,themes:all,name:null }
        
front_programme_details:
    path:     /{slug}
    defaults: { _controller: FrontGeneralBundle:Programme:details }

front_programme_reservation:
    path:     /{slug}/reservation/{periode}
    defaults: { _controller: FrontGeneralBundle:Programme:reservation }
    requirements:
        periode:  \d+

front_programme_thankyou:
    path:     /{slug}/success/{reservation}
    defaults: { _controller: FrontGeneralBundle:Programme:success }
    requirements:
        reservation:  \d+

