front_resabooking_liste:
    path:     /{page}/{region}/{debut}/{fin}/{room1}/{room2}/{room3}/{room4}/{room5}
    defaults: { _controller: FrontGeneralBundle:ResaBooking:liste,page:1,region:Hammamet,debut:all,fin:all,room1:2,room2:null,room3:null,room4:null,room5:null}
    requirements:
            page:  \d+