front_voyageorganise_accueil:
    path:     /
    defaults: { _controller: FrontGeneralBundle:VoyageOrganise:accueil }
    
front_voyageorganise_liste:
    path:     /liste/{page}/{themes}/{destinations}/{pays}/{sort}/{direction}/{name}
    defaults: { _controller: FrontGeneralBundle:VoyageOrganise:liste,page:1,themes:all,destinations:all,pays:all,name:null ,sort:v.libelle,direction:asc }
    requirements:
        page:  \d+

front_voyageorganise_sort:
    path:     /sort/{themes}/{destinations}/{pays}/{name}
    defaults: { _controller: FrontGeneralBundle:VoyageOrganise:sort,themes:all,destinations:all,pays:all,name:null }
        
front_voyageorganise_hotel_ajax:
    path:     /front_voyageorganise_hotel_ajax
    defaults: { _controller: FrontGeneralBundle:VoyageOrganise:packToHotelsAjax }
        
front_voyageorganise_details:
    path:     /{slug}
    defaults: { _controller: FrontGeneralBundle:VoyageOrganise:details }
    
front_voyageorganise_thankyou:
    path:     /{slug}/success/{reservation}
    defaults: { _controller: FrontGeneralBundle:VoyageOrganise:success }
    requirements:
        reservation:  \d+
        
front_voyageorganise_reservation:
    path:     /{slug}/{pack}
    defaults: { _controller: FrontGeneralBundle:VoyageOrganise:reservation }
    requirements:
        periode:  \d+