#Gestion des centres
back_bienetre_ref_centre:
    path:     /centre/{id}
    defaults: { _controller: BackBienEtreBundle:Referentiel:centre,id:null }
    requirements:
        id:  \d+
        
delete_back_bienetre_centre:
    path:     /delete_back_bienetre_centre/{id}
    defaults: { _controller: BackBienEtreBundle:Referentiel:deleteCentre }
    
back_bienetre_ref_centre_photo:
    path:     /centre/{id}/photoCentre/{id2}
    defaults: { _controller: BackBienEtreBundle:Referentiel:centrePhoto,id2:null }
    requirements:
        id:  \d+
 
delete_photo_centre:
    path:     /delete_photo_centre/{id}
    defaults: { _controller: BackBienEtreBundle:Referentiel:deletePhotoCentre }
    
    
#Gestion des produits   
back_bienetre_ref_produit:
    path:     /produit/{id}
    defaults: { _controller: BackBienEtreBundle:Referentiel:produit,id:null }
    requirements:
        id:  \d+
        
delete_back_bienetre_produit:
    path:     /delete_back_bienetre_produit/{id}
    defaults: { _controller: BackBienEtreBundle:Referentiel:deleteProduit }
    
back_bienetre_ref_produit_tarif:
    path:     /produit/{id}/tarifProduit/{id2}
    defaults: { _controller: BackBienEtreBundle:Referentiel:produitTarif,id2:null }
    requirements:
        id:  \d+
 
delete_tarif_produit:
    path:     /delete_tarif_produit/{id}
    defaults: { _controller: BackBienEtreBundle:Referentiel:deleteTarifProduit }
    
back_bienetre_ref_produit_photo:
    path:     /produit/{id}/photoProduit/{id2}
    defaults: { _controller: BackBienEtreBundle:Referentiel:produitPhoto,id2:null }
    requirements:
        id:  \d+
 
delete_photo_produit:
    path:     /delete_photo_produit/{id}
    defaults: { _controller: BackBienEtreBundle:Referentiel:deletePhotoProduit }