back_crm_client_liste:
    path:     /liste/{page}
    defaults: { _controller: BackUserBundle:CRMClient:liste,page:1 }

back_crm_client_ajouter:
    path:     /ajouter/{id}
    defaults: { _controller: BackUserBundle:CRMClient:ajouter,id:null }
    
back_crm_client_profil:
    path:      /profil/{id}
    defaults: { _controller: BackUserBundle:CRMClient:profil }
    
back_crm_client_profil_contact:
    path:     /profil/{id}/contact/{id2}/{page}
    defaults: { _controller: BackUserBundle:CRMClient:profilContact,id2:null,page:1 }
    requirements:
        id:  \d+
    
back_crm_client_profil_contact_delete:
    path:      /supprimer_profil_contact/{id}
    defaults: { _controller: BackUserBundle:CRMClient:deleteProfilContact,id:null,page:1 }
    
back_crm_client_delete:
    path:     /supprimerClient/{id}
    defaults: { _controller: BackUserBundle:CRMClient:delete }
    
back_crm_client_contacts:
    path:     /contactsClient/{id}/{page}
    defaults: { _controller: BackUserBundle:CRMClient:contacts,id:null,page:1 }
    
back_crm_client_contact_delete:
    path:     /supprimerContactClient/{id}
    defaults: { _controller: BackUserBundle:CRMClient:deleteContact }