back_resabooking_hotels_liste:
    path:     /{page}
    defaults: { _controller: BackResaBookingBundle:Hotels:liste,page:1 }
    requirements:
        page:  \d+

back_resabooking_hotels_refresh:
    path:     /refresh
    defaults: { _controller: BackResaBookingBundle:Hotels:refresh }