amicale:
    path:     /amicale/{id}
    defaults: { _controller: BackAdministrationBundle:B2b:amicale,id:null }

delete_amicale:
    path:     /delete_amicale/{id}
    defaults: { _controller: BackAdministrationBundle:B2b:deleteAmicale }

amicale_hotel:
    path:     /amicale/{id}/hotels
    defaults: { _controller: BackAdministrationBundle:B2b:hotels }

amicale_client:
    path:     /amicale/{id}/clients/{id2}
    defaults: { _controller: BackAdministrationBundle:B2b:clients,id2:null }

convention_amicale:
    path:     /convention/{id}
    defaults: { _controller: BackAdministrationBundle:B2b:convention,id:null }

delete_convention_amicale:
    path:     /delete_convention_amicale/{id}
    defaults: { _controller: BackAdministrationBundle:B2b:deleteConvention }
