amicale:
    path:     /amicale/{id}
    defaults: { _controller: BackAdministrationBundle:B2b:amicale,id:null }

delete_amicale:
    path:     /delete_amicale/{id}
    defaults: { _controller: BackAdministrationBundle:B2b:deleteAmicale }

amicale_client:
    path:     /amicale/{id}/clients/{id2}
    defaults: { _controller: BackAdministrationBundle:B2b:clients,id2:null }

delete_amicale_client:
    path:     /delete_amicale_client/{id}
    defaults: { _controller: BackAdministrationBundle:B2b:deleteClient }