configuration_agence:
    path:     /agence
    defaults: { _controller: BackAdministrationBundle:Configuration:agence }

configuration_etat:
    path:     /etat/{id}
    defaults: { _controller: BackAdministrationBundle:Configuration:etat,id:null }

configuration_etat_supprimer:
    path:     /configuration_etat_supprimer/{id}
    defaults: { _controller: BackAdministrationBundle:Configuration:etatDelete }