configuration_agence:
    path:     /agence
    defaults: { _controller: BackAdministrationBundle:Configuration:agence }
    
configuration_pointVente:
    path:     /pointVente/{id}
    defaults: { _controller: BackAdministrationBundle:Configuration:pointVente,id:null }
    
configuration_pointVente_delete:
    path:     /configuration_pointVente_delete/{id}
    defaults: { _controller: BackAdministrationBundle:Configuration:pointVenteDelete }

configuration_etat:
    path:     /etat/{id}
    defaults: { _controller: BackAdministrationBundle:Configuration:etat,id:null }

configuration_etat_supprimer:
    path:     /configuration_etat_supprimer/{id}
    defaults: { _controller: BackAdministrationBundle:Configuration:etatDelete }

configuration_produit:
    path:     /produit/{id}
    defaults: { _controller: BackAdministrationBundle:Configuration:produit,id:null }

configuration_produit_delete:
    path:     /produit_delete/{id}
    defaults: { _controller: BackAdministrationBundle:Configuration:produitDelete }

configuration_tva:
    path:     /tva/{id}
    defaults: { _controller: BackAdministrationBundle:Configuration:tva,id:null }

configuration_tva_delete:
    path:     /tva_delete/{id}
    defaults: { _controller: BackAdministrationBundle:Configuration:tvaDelete }