group:
    path:     /groupe/{id}
    defaults: { _controller: BackAdministrationBundle:Users:group,id:null }

delete_group:
    path:     /delete_group/{id}
    defaults: { _controller: BackAdministrationBundle:Users:deleteGroup }

user:
    path:     /user/{id}/{password}
    defaults: { _controller: BackAdministrationBundle:Users:user,id:null,password:null }

delete_user:
    path:     /delete_user/{id}
    defaults: { _controller: BackAdministrationBundle:Users:deleteUser }

enable_user:
    path:     /enable_user/{id}
    defaults: { _controller: BackAdministrationBundle:Users:enableUser }

back_emails:
    path:     /emails/{id}
    defaults: { _controller: BackAdministrationBundle:Users:emails,id:null }    

back_email_delete:
    path:     /back_email_delete/{id}
    defaults: { _controller: BackAdministrationBundle:Users:deleteEmail }    
