Hotel_Tunisie_Referentiel:
    resource: "@BackHotelTunisieBundle/Resources/config/routing/referentiel.yml"
    prefix:   /referentiel

Hotel_Tunisie_Configuration:
    resource: "@BackHotelTunisieBundle/Resources/config/routing/configuration.yml"
    prefix:   /configuration

Hotel_Tunisie_Reservation:
    resource: "@BackHotelTunisieBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation

Hotel_Tunisie_hotels:
    resource: "@BackHotelTunisieBundle/Resources/config/routing/hotels.yml"
    prefix:   /hotels

Saisons:
    resource: "@BackHotelTunisieBundle/Resources/config/routing/saisons.yml"
    prefix:   /hotels

Hotel_Tunisie_SaisonBase:
    resource: "@BackHotelTunisieBundle/Resources/config/routing/saison_base.yml"
    prefix:   /hotels

Hotel_Tunisie_hotels_deleted:
    resource: "@BackHotelTunisieBundle/Resources/config/routing/hotelsDeleted.yml"
    prefix:   /deleted_hotels