Hotel_Tunisie_Referentiel:
    resource: "@BackHotelTunisieBundle/Resources/config/routing/referentiel.yml"
    prefix:   /referentiel

Hotel_Tunisie_hotels:
    resource: "@BackHotelTunisieBundle/Resources/config/routing/hotels.yml"
    prefix:   /hotels