services:
    reservationBackListnerSHT:
          class: Back\HotelTunisieBundle\Listener\ReservationBackListnerSHT
          arguments:
              - @service_container
              - @session
              - @doctrine.orm.entity_manager
          tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    ReportingSHTExtensionTwig:
      class: Back\HotelTunisieBundle\Twig\Extension\ReportingExtension
      tags:
          - { name: twig.extension }
      arguments:
          em: "@doctrine.orm.entity_manager"
          container: "@service_container"

    SaisonExtension:
      class: Back\HotelTunisieBundle\Twig\Extension\SaisonExtension
      tags:
          - { name: twig.extension }
      arguments:
          em: "@doctrine.orm.entity_manager"
          container: "@service_container"
        
    saisons:
        class: Back\HotelTunisieBundle\Services\Saisons
        arguments: [ @doctrine.orm.entity_manager ]
        
    library:
        class: Back\HotelTunisieBundle\Services\Library
        
    lignes:
        class: Back\HotelTunisieBundle\Services\Lignes
        arguments: [ @doctrine.orm.entity_manager, @session, @service_container ]
        
    reservation:
        class: Back\HotelTunisieBundle\Services\ReservationService
        arguments:
            - @doctrine.orm.entity_manager
            - @session
            - @service_container
            - @mailer
            - @templating
            
