services:
    FunctionExtensions:
      class: Back\HotelTunisieBundle\Twig\Extension\FunctionExtension
      tags:
          - { name: twig.extension }
      arguments:
          em: "@doctrine.orm.entity_manager"
          container: "@service_container"
        
    saisons:
        class: Back\HotelTunisieBundle\Services\Saisons
        arguments: [ @doctrine.orm.entity_manager ]
        
    library:
        class: Back\HotelTunisieBundle\Services\Library
        
    reservation:
        class: Back\HotelTunisieBundle\Services\Reservation
        arguments: [ @doctrine.orm.entity_manager, @session, @service_container ]
        
    lignes:
        class: Back\HotelTunisieBundle\Services\Lignes
        arguments: [ @doctrine.orm.entity_manager, @session, @service_container ]
        
        