accueil:
    path:     /
    defaults: { _controller: FrontGeneralBundle:Default:accueil }

ole_booking_hotels:
    path:     /hotels_dans_le_monde
    defaults: { _controller: FrontGeneralBundle:Default:oleBooking }

ole_locaton_cars:
    path:     /location_voitures
    defaults: { _controller: FrontGeneralBundle:Default:oleLocation }

under_construction:
    path:     /under_construction
    defaults: { _controller: FrontGeneralBundle:Default:underConstruction }

front_hoteltunisie:
    resource: "@FrontGeneralBundle/Resources/config/routing/hoteltunisie.yml"
    prefix:   /HotelTunisie

front_voyageorganise:
    resource: "@FrontGeneralBundle/Resources/config/routing/voyageorganise.yml"
    prefix:   /VoyageOrganise

front_programme:
    resource: "@FrontGeneralBundle/Resources/config/routing/programme.yml"
    prefix:   /Programme
