accueil:
    path:     /
    defaults: { _controller: FrontGeneralBundle:Default:accueil }

ole_booking_hotels:
    path:     /hotels_dans_le_monde
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'FrontGeneralBundle::ole_booking.html.twig'

ole_locaton_cars:
    path:     /location_voitures
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'FrontGeneralBundle::ole_location.html.twig'

ole_locaton_cars_monde:
    path:     /location_voitures_monde
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'FrontGeneralBundle::ole_location_monde.html.twig'

under_construction:
    path:     /under_construction
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'FrontGeneralBundle::under_construction.html.twig'

front_hoteltunisie:
    resource: "@FrontGeneralBundle/Resources/config/routing/hoteltunisie.yml"
    prefix:   /HotelTunisie

front_resabooking:
    resource: "@FrontGeneralBundle/Resources/config/routing/resabooking.yml"
    prefix:   /reservation_immediate

front_voyageorganise:
    resource: "@FrontGeneralBundle/Resources/config/routing/voyageorganise.yml"
    prefix:   /VoyageOrganise

front_programme:
    resource: "@FrontGeneralBundle/Resources/config/routing/programme.yml"
    prefix:   /Programme

front_billetterie:
    resource: "@FrontGeneralBundle/Resources/config/routing/billetterie.yml"
    prefix:   /Billetterie

front_maritime:
    resource: "@FrontGeneralBundle/Resources/config/routing/maritime.yml"
    prefix:   /Maritime

front_bienetre:
    resource: "@FrontGeneralBundle/Resources/config/routing/bienetre.yml"
    prefix:   /BienEtre

front_paiement:
    resource: "@FrontGeneralBundle/Resources/config/routing/paiement.yml"
    prefix:   /