services:        
    reservationlistner:
      class: Front\GeneralBundle\Listener\ReservationListner
      arguments:
          - @service_container
          - @session
          - @doctrine.orm.entity_manager
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }     