services:        
    reservationlistnerSHT:
      class: Front\GeneralBundle\Listener\ReservationListnerSHT
      arguments:
          - @service_container
          - @session
          - @doctrine.orm.entity_manager
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    reservationlistnerVO:
      class: Front\GeneralBundle\Listener\ReservationListnerVO
      arguments:
          - @service_container
          - @session
          - @doctrine.orm.entity_manager
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    reservationlistnerPR:
      class: Front\GeneralBundle\Listener\ReservationListnerPR
      arguments:
          - @service_container
          - @session
          - @doctrine.orm.entity_manager
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }