<?php

namespace Back\HotelTunisieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends EntityRepository
{
    public function getDeletedList()
    {
        $query=$this->createQueryBuilder('a');
        $query      ->where($query->expr()->isNotNull('a.deletedAt'));
        return $query->getQuery()->getResult();
    }
}
