back_programmes_reservation_validation:
    path:     /valider/{id}
    defaults: { _controller: BackProgrammeBundle:Reservation:valider }
    
back_programmes_reservation_total:
    path:     /total/{id}
    defaults: { _controller: BackProgrammeBundle:Reservation:total }

back_programmes_reservation_consulter:
    path:     /consulter/{id}
    defaults: { _controller: BackProgrammeBundle:Reservation:consulter }

back_programmes_reservation_annuler:
    path:     /annuler/{id}
    defaults: { _controller: BackProgrammeBundle:Reservation:annuler }

back_programmes_reservation_supprimer:
    path:     /delete/{id}
    defaults: { _controller: BackProgrammeBundle:Reservation:delete }

back_programmes_reservation_priseencharge:
    path:     /priseEnCharge/{id}
    defaults: { _controller: BackProgrammeBundle:Reservation:priseEnCharge }

back_programmes_reservation:
    path:     /liste/{page}/{etat}/{sort}/{direction}
    defaults: { _controller: BackProgrammeBundle:Reservation:liste,page:1,etat:1,sort:r.id,direction:desc }

back_programmes_reservation_ligne_supprimer:
    path:     /reservation_ligne_supprimer/{id}
    defaults: { _controller: BackProgrammeBundle:Reservation:deleteLigne }

back_programmes_reservation_ligne_edit:
    path:     /reservation_ligne_edit/{id}
    defaults: { _controller: BackProgrammeBundle:Reservation:editLigne }

back_programmes_reservation_remise:
    path:     /reservation_remise/{id}
    defaults: { _controller: BackProgrammeBundle:Reservation:remise }
    
back_programmes_reservation_add_sousetats:
    path:     /add_sousetats
    defaults: { _controller: BackProgrammeBundle:Reservation:addSousEtats }

ajax_reservationPR_to_SousEtats:
    path:     /ajax_reservationPR_to_SousEtats
    defaults: { _controller: BackProgrammeBundle:Reservation:ajaxSousEtats }