espace_client_routes:
    resource: "@EspaceClientBundle/Resources/config/routing/espace_client.yml"
    prefix:   /espace_client

espace_amicales_routes:
    resource: "@EspaceClientBundle/Resources/config/routing/espace_amicale.yml"
    prefix:   /espace_amicale