back_commercial_config:
    resource: "@BackCommercialBundle/Resources/config/routing/config.yml"
    prefix:   /
    
back_commercial_users:
    resource: "@BackCommercialBundle/Resources/config/routing/users.yml"
    prefix:   /
    
back_commercial_reglement:
    resource: "@BackCommercialBundle/Resources/config/routing/reglement.yml"
    prefix:   /